### ISSUE TITLE
Extension activation time is really high

### ISSUE THREAD

**Issue by Philip-Trettner** [stef-levesque/vscode-shader#11]
With the new "Show Running Extensions" feature I noticed that this extension has an abnormally high start-up time. Most extensions start in 30-100ms, this one in 700+ (tested it multiple times).

Is there an easy way to fix this?

- Extension Name: shader
- Extension Version: 1.1.2
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 731,
		"activateCallTime": 0,
		"activateResolvedTime": 12,
		"activationEvent": "onLanguage:glsl"
	}
}
```

**Comment by stef-levesque** [comment]
The activation function should only register HLSL provider, so it shouldn't take that long (I assume `activateResolvedTime: 12ms` is that call)

What is bothering me is `"codeLoadingTime": 731ms`. I wonder if it comes from the unnecessary packages in `node_modules`

**Comment by Trass3r** [comment]
Same here, 1 second to load it.
And worse, it runs every time at startup.

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 936,
		"activateCallTime": 1,
		"activateResolvedTime": 27,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CADENAS.vscode-glsllint",
				"_lower": "cadenas.vscode-glsllint"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by stef-levesque** [comment]
Please log this issue at vscode-glsllint
