### ISSUE TITLE
Issues with Ionide F#

### ISSUE THREAD

**Issue by geoeo** [stef-levesque/vscode-shader#12]
This plugin disables syntax highlighting, autocompletion etc for Ionide-fsharp

https://github.com/ionide/ionide-vscode-fsharp

**Comment by stef-levesque** [comment]
It might be a problem with the file extension association.
What kind of file exactly is having this problem ?

**Comment by geoeo** [comment]
It disables syntax highlighting,autocompletion etc for ionide-f#.

**Comment by stef-levesque** [comment]
FSharp and GLSL fragment shader use the same extension (*.fs)

You can specify in your VSCode user settings which language you want to associate it.
Adding this in your user or workspace settings should fix your issue.

```json
    "files.associations": {
        "*.fs": "fsharp"
    }
```

**Comment by geoeo** [comment]
Of course. fs for fragment shader. Thanks!
