### ISSUE TITLE
C++ raw string highlighting

### ISSUE THREAD

**Issue by davl3232** [stef-levesque/vscode-shader#13]
Is it possible to highlight shader code inside C++11 raw strings?

For example, highlight this.

```
R"(
#version 420 core

void main(void)
{
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
}
)"
```

**Comment by stef-levesque** [comment]
Hm, I'm not sure if this is possible. I know we can specify sub-language, like javascript in an HTML file, but it is hard to detect here, just from the context, that it correspond to a specific shader language.

**Comment by davl3232** [comment]
Raw string literals in C++ follow this syntax:
```
R "delimiter( raw_characters )delimiter"
```
Delimiter is user defined and `)delimiter"`must not be contained inside raw_characters.

It could be detected by using a special delimiter as convention that tells the syntax needed, like: 
```
R"glsl(
#version 420 core

void main(void)
{
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
}
)glsl"
```

**Comment by stef-levesque** [comment]
Hm, that's right, I forgot this C++11 feature.

I'll double-check the VSCode documentation, to see if it's possible to add `embeddedLanguages` to C++ from an extension.
