### ISSUE TITLE
Can not reformat .glsl

### ISSUE THREAD

**Issue by xdestiny110** [stef-levesque/vscode-shader#16]
I want to reformat some glsl code. But it tell me that I did not install format file.
When I change associate file to HLSL it work.
Is there something wrong?

**Comment by stef-levesque** [comment]
This extension do not support formating for GLSL, or at least not yet.

You might want to have a look at the following extensions
* https://marketplace.visualstudio.com/items?itemName=CADENAS.vscode-glsllint
* https://marketplace.visualstudio.com/items?itemName=xaver.clang-format
