### ISSUE TITLE
Formatting Code (Experimental) Require MS CppTools to be installed

### ISSUE THREAD

**Issue by ssatguru** [stef-levesque/vscode-shader#18]
Per document
"Formatting Code (Experimental) Require MS CppTools to be installed"

How does this work?
I installed MS CppTools but I still get
"There is no document formatter for 'glsl'-files installed."

**Comment by stef-levesque** [comment]
Advanced features like Formatting and Auto-completion is not yet supported for GLSL.
Although, work is currently in progress :)
