### ISSUE TITLE
Highlight WebGL shaders embedded in HTML file

### ISSUE THREAD

**Issue by RoryDungan** [stef-levesque/vscode-shader#20]
In WebGL we can specify shaders in separate files or embedded in an HTML file like this:
```html
<html>
  <script id="vertex-shader" type="x-shader/x-vertex">
    attribute vec4 vPosition;

    void main()
    {
      gl_Position = vPosition;
    }
  </script>
</html>
```

VSCode already has highlighting for embedded JS in an HTML file so I think this should be possible, although I'm not sure if it's within the realm of this extension or would require a change in the way VS Code parses HTML. The shader is identifiable as the text inside any <script> tag with the `type` property set to `x-shader/x-vertex` or `x-shader/x-fragment`. Syntax should be the same as OpenGL ES 2.0. 

I could potentially have a look into implementing this is you think it's a worthwhile addition but don't have any experience in writing VS Code extensions so any help or ideas would be great. What do you reckon?

**Comment by svetx** [comment]
@stef-levesque How long will your sabbatical leave last?
