### ISSUE TITLE
Add enhanced icon

### ISSUE THREAD

**Issue by Andari85** [stef-levesque/vscode-shader#37]
I did render a new version of the icon of this addon; correct perspective of texts on the cube and proper transparency. (The current one disturbed me that much in my sidebar, that I thought I create one for you.)
I uploaded a 128x128 and a 2048x2048 version.
Please replace the current one.
![Shader-Support-Icon-Small](https://user-images.githubusercontent.com/40171926/86608983-8a5ec180-bfab-11ea-9b16-da40f5bffa45.png)
![Shader-Support-Icon-Large](https://user-images.githubusercontent.com/40171926/86609017-98144700-bfab-11ea-9680-ceb6c45e25d2.png)

**Comment by Tyriar** [comment]
This would be nice, it's definitely one of the uglier icons in my installed extensions.

@stef-levesque I can put together a PR using the above image if it would get merged/published?

**Comment by stef-levesque** [comment]
I have to agree, my icon is not great.

Yes, please create a PR and I'll update the extension over the weekend.

Thanks @Andari85 @Tyriar

**Comment by Tyriar** [comment]
@stef-levesque great! It's done in https://github.com/stef-levesque/vscode-shader/pull/40, should be a very safe PR to merge as it only changes the image.
