### ISSUE TITLE
Incorrect GLSL highlighting

### ISSUE THREAD

**Issue by MrVallentin** [stef-levesque/vscode-shader#6]
Writing `#ifdef` and everything is correctly highlighted. However writing `#if defined(...)` causes the first line after to not be highlighted, and just plain white. Everything after that line is correctly highlighted again though.

**Screenshot:**
![](http://i.imgur.com/i7GWr0n.png)

_This also includes `#elif defined(...)`._

**Comment by stef-levesque** [comment]
Can you try forcing the language as HLSL, see if this solve it ?
If so, I'll fix the glsl.tmlanguage quickly

**Comment by MrVallentin** [comment]
Changing it to HLSL works!

**Comment by stef-levesque** [comment]
Finally fixed :)
Please download version 0.2.3
