### ISSUE TITLE
Can't reformat .shader files? or I am doing wrong step.

### ISSUE THREAD

**Issue by lifangjie** [stef-levesque/vscode-shader#7]

**Comment by stef-levesque** [comment]
.shader files are already associated by default to ShaderLab syntax. ( see issue #2 )

But you can 'Configure file association' to overwrite that (see "file.associations" in your settings.json

**Comment by lifangjie** [comment]
I know, high light works right, auto complete check. but reformat? are u sure it works?

**Comment by stef-levesque** [comment]
Hm, sorry I misunderstand you question... Yes, it would be interesting to have a format option for shader files. But ShaderLab syntax is owned by [vscode](https://github.com/Microsoft/vscode)

**Comment by lifangjie** [comment]
e.... Apologize for my pool English, thanks.
