### ISSUE TITLE
Please consider giving us a way to add custom extensions for shader files.

### ISSUE THREAD

**Issue by ObsidianPC** [stef-levesque/vscode-shader#8]
Hi there,

I love your Shader Languages package for VSC!  

I work in game development and our shaders often come with game-engine specific file extensions, though the code within is still HLSL, GLSL, or CG.  

Would it be possible for you to add a place where I can add custom file extensions to be handled by your highlighting package?

Thanks for the time and effort - it makes life much better!

~Alex

**Comment by stef-levesque** [comment]
Well, hello there fellow game developper! :)

You can open one of your custom file and click on the lower-right Language button to choose 'Configure file association' 

You can also overwrite any association in the"file.associations" section of your settings.json

i.e.
`
    "files.associations": {
        "*.abc": "xml",
        "*.fsh": "glsl",
        "*.shader": "hlsl"
    },
`

Hope it helps
